name: "Generate tags"
description: "Genertaes semver compatible tags for docker images based on a slug reference (i.e, / converted to _)"
inputs:
  slug:
    description: "the branch/tag reference in slug format (/ converted to _)"
    required: true
  image-name:
    description: A docker image name. e.g, myrepo/myimage
    required: false
  prefix:
    description: "A prefix to append before all tag names (e.g, debug)"
    required: false
    default: ""
  suffix:
    description: "A suffix to append after all tag names (e.g, a client-specific suffix)"
    required: false
    default: ""
  arch:
    description: "An optional architecture suffix to append after all tag names (e.g, amd64, arm64, etc). This is useful when building multi-arch images."
    required: false
  allow-latest-tag:
    description: "if false, will prevent a latest tag being added, even if this is the newest version"
    required: false
    default: "true"
  is-primary:
    description: "if true, will add the default latest even when used with prefix or suffix, when the semver slug is the latest version"
    required: false
    default: "false"
  docker-user:
    description: The docker hub user account (needed if image is private)
    required: false
  docker-pass:
    description: The docker hub account password (needed if image is private)
    required: false
runs:
  using: "composite"
  steps:
    - name: Inputs
      shell: bash
      run: |
        echo "Given slug was: ${{ inputs.slug }}"
        echo "Given prefix was: ${{ inputs.prefix }}"
        echo "Given suffix was: ${{ inputs.suffix }}"
        echo "Given image was: ${{ inputs.image-name }}"
        echo "Given arch was: ${{ inputs.arch }}"
        echo "Allow latest tag: ${{ inputs.allow-latest-tag }}"
        echo "Is primary tag: ${{ inputs.is-primary }}"
    - id: tag-generator
      name: "Process slug"
      env:
        ACTION_PATH: "${{ github.action_path }}"
        DOCKER_USER: "${{ inputs.docker-user }}"
        DOCKER_PASS: "${{ inputs.docker-pass }}"
        DOCKER_IMAGE: "${{ inputs.image-name }}"
      run: |
        chmod 777 "$ACTION_PATH"/tag-gen.sh "$ACTION_PATH"/dockertags.sh
        cd "$ACTION_PATH"
        echo "$(\
          "$ACTION_PATH"/tag-gen.sh ${{ inputs.slug }}${DOCKER_USER:+ -u=$DOCKER_USER}${DOCKER_PASS:+ -p=$DOCKER_PASS}${DOCKER_IMAGE:+ -i=$DOCKER_IMAGE}\
          -prefix=${{ inputs.prefix }} \
          -suffix=${{ inputs.suffix }} \
          -arch=${{ inputs.arch }} \
          --allow-latest-tag=${{ inputs.allow-latest-tag }} \
          --is-primary=${{ inputs.is-primary }} \
        )"
      shell: bash
outputs:
  tags:
    description: "A newline separated list of tags"
    value: ${{ steps.tag-generator.outputs.tags }}
  slug:
    description: "A new slug with any leading v stripped off for semvers"
    value: "${{ steps.tag-generator.outputs.slug }}"
